language: ruby

cache: bundler

rvm:
  - 2.0.0

sudo: false

addons:
  apt:
    packages:
    - dnsutils

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - rvm @global do gem uninstall bundler -x && gem install bundler -v '~> 1.5.2'  # For Vagrant 1.5
