language: ruby

cache: bundler

rvm:
  - 2.0.0

sudo: false

addons:
  apt:
    packages:
    - dnsutils

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - rvm @global do gem uninstall bundler -x && gem install bundler -v '>= 1.5.2, <= 1.10.5'  # For Vagrant 1.7.4

notifications:
  email:
    on_success: never
